# Generated by Django 5.1.2 on 2024-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=0, max_digits=2)),
                ('description', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
